version: '3.8'

services:
  db:
    image: postgres:14   # 🔥 use older stable version
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: skin_disease_db
    ports:
      - "5436:5432"